// <auto-generated />
using System;
using Compliance_Platform.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compliance_Platform.Migrations
{
    [DbContext(typeof(CompPlatformDbContext))]
    [Migration("20250501235620_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformAnswers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int");

                    b.Property<string>("Treść")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WagaRyzyka")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionsId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudytorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompPlatformQuestionnairesId")
                        .HasColumnType("int");

                    b.Property<int>("CompPlatformToolId")
                        .HasColumnType("int");

                    b.Property<string>("CompPlatformUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataSprawdzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZlozenia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KalkulacjaRyzyka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PoziomRyzyka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AudytorId");

                    b.HasIndex("CompPlatformQuestionnairesId");

                    b.HasIndex("CompPlatformToolId");

                    b.HasIndex("CompPlatformUserId");

                    b.ToTable("InstancesTool");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformInstanceAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompPlatformInstanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOdpowiedzi")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<string>("OdpowiedzTekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpcjaOdpowiedziId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("int");

                    b.Property<decimal>("WagaRyzykaPojedyncza")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WnioskujacyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompPlatformInstanceId");

                    b.HasIndex("OpcjaOdpowiedziId");

                    b.HasIndex("QuestionTemplateId");

                    b.HasIndex("WnioskujacyId");

                    b.ToTable("InstanceAnswers");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformQuestionnaires", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionnairesId")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypPytania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WagaRyzyka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Wymagane")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnairesId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPowstania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WlascicielId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WlascicielId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformAnswers", b =>
                {
                    b.HasOne("Compliance_Platform.Model.CompPlatformQuestions", "Questions")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformInstance", b =>
                {
                    b.HasOne("Compliance_Platform.Model.CompPlatformUser", "Audytor")
                        .WithMany()
                        .HasForeignKey("AudytorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Compliance_Platform.Model.CompPlatformQuestionnaires", "CompPlatformQuestionnaires")
                        .WithMany()
                        .HasForeignKey("CompPlatformQuestionnairesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compliance_Platform.Model.CompPlatformTool", "CompPlatformTool")
                        .WithMany()
                        .HasForeignKey("CompPlatformToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compliance_Platform.Model.CompPlatformUser", null)
                        .WithMany("ToolInstance")
                        .HasForeignKey("CompPlatformUserId");

                    b.Navigation("Audytor");

                    b.Navigation("CompPlatformQuestionnaires");

                    b.Navigation("CompPlatformTool");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformInstanceAnswer", b =>
                {
                    b.HasOne("Compliance_Platform.Model.CompPlatformInstance", "CompPlatformInstance")
                        .WithMany("Answers")
                        .HasForeignKey("CompPlatformInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compliance_Platform.Model.CompPlatformAnswers", "OpcjaOdpowiedzi")
                        .WithMany()
                        .HasForeignKey("OpcjaOdpowiedziId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Compliance_Platform.Model.CompPlatformQuestions", "CompPlatformQuestions")
                        .WithMany()
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Compliance_Platform.Model.CompPlatformUser", "Wnioskujacy")
                        .WithMany()
                        .HasForeignKey("WnioskujacyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompPlatformInstance");

                    b.Navigation("CompPlatformQuestions");

                    b.Navigation("OpcjaOdpowiedzi");

                    b.Navigation("Wnioskujacy");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformQuestionnaires", b =>
                {
                    b.HasOne("Compliance_Platform.Model.CompPlatformUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformQuestions", b =>
                {
                    b.HasOne("Compliance_Platform.Model.CompPlatformQuestionnaires", "Questionnaires")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnairesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformTool", b =>
                {
                    b.HasOne("Compliance_Platform.Model.CompPlatformUser", "Wlasciciel")
                        .WithMany("Tool")
                        .HasForeignKey("WlascicielId");

                    b.Navigation("Wlasciciel");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformInstance", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformQuestionnaires", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformQuestions", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Compliance_Platform.Model.CompPlatformUser", b =>
                {
                    b.Navigation("Tool");

                    b.Navigation("ToolInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
